# Generated by Django 4.2.2 on 2023-07-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialisation', models.CharField(choices=[('Chest', 'Chest'), ('Heart', 'Heart'), ('General', 'General'), ('Orthopaedic', 'Orthopaedic')], max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
