# Generated by Django 4.2.2 on 2023-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_deal_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
