# Generated by Django 4.2.2 on 2023-07-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_entered_by'),
        ('doctor', '0007_alter_deal_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
